# remember to clone the themes repo with `git clone https://github.com/alacritty/alacritty-theme`
import = ["~/.config/alacritty/alacritty-theme/themes/dracula.toml"]
# import = ["~/.config/alacritty/rose-pine-moon.toml"]

[cursor]
thickness = 0.2

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "Control"

[selection]
save_to_clipboard = true

[window]
blur = true
opacity = 0.7
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 110
lines = 30

[keyboard]
bindings = [
{ key = "N", mods="Control", action="CreateNewWindow"},
{ key = "H", mods="Command", action="ReceiveChar"},
{ key = "H", mods="Command|Alt", action="ReceiveChar"},
]
