model = "gpt-5.6-sol"
# model_provider = "azure"
model_reasoning_effort = "medium"
personality = "pragmatic"
plan_mode_reasoning_effort = "high"
approvals_reviewer = "user"

notify = ["/Users/tudoroancea/dotfiles/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]

[model_providers.azure]
name = "pave"
base_url = "https://pave-openai-sweden-central.cognitiveservices.azure.com/openai/v1"
env_key = "AZURE_OPENAI_API_KEY"
wire_api = "responses"

[projects."/Users/tudoroancea/dev/tinyanvil"]
trust_level = "trusted"

[projects."/Users/tudoroancea/dev/tinygrad"]
trust_level = "trusted"

[projects."/Users/tudoroancea/dev/zigbind"]
trust_level = "trusted"

[projects."/Users/tudoroancea/dev/tanstack-start-pwa/codex"]
trust_level = "trusted"

[projects."/Users/tudoroancea/dev/laopt"]
trust_level = "untrusted"

[projects."/Users/tudoroancea/dev/hexahedron2/hexahedron2"]
trust_level = "trusted"

[projects."/Users/tudoroancea/dotfiles"]
trust_level = "untrusted"

[projects."/Users/tudoroancea/dev/hexahedron2"]
trust_level = "untrusted"

[projects."/Users/tudoroancea/Library/Mobile Documents/iCloud~md~obsidian/Documents/Ted/phd/kernels"]
trust_level = "untrusted"

[projects."/Users/tudoroancea/dev/piqp"]
trust_level = "untrusted"

[projects."/Users/tudoroancea/dev/bourbaki"]
trust_level = "trusted"

[projects."/Users/tudoroancea/dev/anvil"]
trust_level = "trusted"

[projects."/Users/tudoroancea/dev/babyfoot_league"]
trust_level = "trusted"

[projects."/Users/tudoroancea/dev/openforces"]
trust_level = "trusted"

[projects."/Users/tudoroancea/.local/share/opencode/worktree/007c7198c77e5cac072cb1aa9b99ccd580647781/curious-otter"]
trust_level = "trusted"

[projects."/Users/tudoroancea/dev/tests/bun-hono"]
trust_level = "trusted"

[projects."/Users/tudoroancea/dev/t3code"]
trust_level = "trusted"

[projects."/Users/tudoroancea/dev/robotics-practicals"]
trust_level = "trusted"

[projects."/Users/tudoroancea/Desktop/phd/candidacy"]
trust_level = "trusted"

[projects."/Users/tudoroancea/dev/controls_challenge"]
trust_level = "trusted"

[projects."/Users/tudoroancea/dev/alloy"]
trust_level = "trusted"

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true

[notice.model_migrations]
"gpt-5.2" = "gpt-5.2-codex"
"gpt-5.3-codex" = "gpt-5.4"

[features]
hooks = true
steer = true
unified_exec = false
multi_agent = true
terminal_resize_reflow = true
goals = true
js_repl = false

[tui]
status_line = ["current-dir", "git-branch", "model-with-reasoning", "context-used"]

[tui.model_availability_nux]
"gpt-5.5" = 3

[marketplaces.openai-bundled]
last_updated = "2026-07-10T06:54:54Z"
source_type = "local"
source = "/Users/tudoroancea/dotfiles/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-07-09T08:14:39Z"
source_type = "local"
source = "/Users/tudoroancea/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[hooks.state]

[hooks.state."/Users/tudoroancea/.codex/hooks.json:stop:0:0"]
trusted_hash = "sha256:40a02a817f671c861fab27b7e6d0dbdef8635e5d230b47afaf57abbe936a6326"

[hooks.state."/Users/tudoroancea/.codex/hooks.json:pre_tool_use:0:0"]
trusted_hash = "sha256:85ec42ddf6bc313aab6f4a6392ff61a7d39ad72c620e6c8fa811ee58cfe33a6d"

[hooks.state."/Users/tudoroancea/.codex/hooks.json:permission_request:0:0"]
trusted_hash = "sha256:7764f6da15ad62a8f82bed5972af52eb5c41b75c7ee20a71d9438810d9f462f5"

[hooks.state."/Users/tudoroancea/.codex/hooks.json:session_start:0:0"]
trusted_hash = "sha256:81e2b489131ef6819bc3f5757d133cd9cb21ca0ade5c83ed12620b36255d2fcb"

[hooks.state."/Users/tudoroancea/.codex/hooks.json:user_prompt_submit:0:0"]
trusted_hash = "sha256:233f09eb9d95a5036f931343fb4911f462e928d777e077c225e8118340266598"

[hooks.state."/Users/tudoroancea/.codex/hooks.json:stop:1:0"]
trusted_hash = "sha256:552d73f461b70cb213cc51a161df0000f886fc42077d8859c9648141aaf98f3f"

[desktop]
appearanceTheme = "system"
appearanceLightCodeThemeId = "rose-pine"
appearanceDarkCodeThemeId = "rose-pine"
useFontSmoothing = true
followUpQueueMode = "steer"
composerEnterBehavior = "cmdIfMultiline"
preventSleepWhileRunning = true
keepRemoteControlAwakeWhilePluggedIn = true
git-branch-prefix = ""
notifications-turn-mode = "always"
conversationDetailMode = "STEPS_PROSE"
worktree-auto-cleanup-enabled = false
show-context-window-usage = true
dock-icon-preference = "codex-system"

[desktop.appearanceLightChromeTheme]
accent = "#d7827e"
contrast = 45
ink = "#575279"
opaqueWindows = true
surface = "#faf4ed"

[desktop.appearanceLightChromeTheme.fonts]
code = "JetBrainsMono Nerd Font"
ui = "JetBrainsMono Nerd Font"

[desktop.appearanceLightChromeTheme.semanticColors]
diffAdded = "#56949f"
diffRemoved = "#797593"
skill = "#907aa9"

[desktop.appearanceDarkChromeTheme]
accent = "#ea9a97"
contrast = 60
ink = "#e0def4"
opaqueWindows = true
surface = "#232136"

[desktop.appearanceDarkChromeTheme.fonts]
code = '"JetBrainsMono Nerd Font"'
ui = '"JetBrainsMono Nerd Font"'

[desktop.appearanceDarkChromeTheme.semanticColors]
diffAdded = "#9ccfd8"
diffRemoved = "#908caa"
skill = "#c4a7e7"

[desktop.open-in-target-preferences]
global = "zed"

[desktop.open-in-target-preferences.perPath]
"/Users/tudoroancea/.codex/worktrees/6dae/babyfoot_league" = "zed"
"/Users/tudoroancea/.codex/worktrees/a167/foxglove_viz_demo" = "ghostty"
"/Users/tudoroancea/.codex/worktrees/b176/anvil" = "zed"
"/Users/tudoroancea/.codex/worktrees/d300/candidacy" = "vscode"
"/Users/tudoroancea/Desktop/phd/candidacy" = "fileManager"
"/Users/tudoroancea/conductor/workspaces/openforces/caracas" = "vscode"
"/Users/tudoroancea/dev/anvil" = "zed"
"/Users/tudoroancea/dev/anvil/.worktrees/tracking-nmpc-benchmarks" = "zed"
"/Users/tudoroancea/dev/anvil/.worktrees/upgrade_tinygrad" = "ghostty"
"/Users/tudoroancea/dev/babyfoot_league" = "zed"

[mcp_servers.node_repl]
args = []
command = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/tudoroancea/.codex"
CODEX_HOME = "/Users/tudoroancea/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "6d25aa7656feac858f3a3bdaea5bcbab0dbfd426c9de8e6931ce90c399ee8e4f,c8b7e809d7cf9e20a57123b2530d476ccec9a01a6230a7b2b924fea7d94d7f4a"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
NODE_REPL_INSTRUCTIONS_USE_CASE_COMPUTER_USE = "Control desktop apps on macOS through Computer Use."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.707.31428"
CODEX_CLI_PATH = "/Applications/ChatGPT.app/Contents/Resources/codex"

[mcp_servers.computer-use]
command = "./Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient"
args = ["mcp"]
cwd = "."
enabled = false
