[tools]
"npm:t3" = "nightly"

[dotfiles]
"~/.zshrc/linux" = { block = """
source $HOME/zen_api_key.sh

source $HOME/.local/bin/env

# nub
export PATH="$HOME/.nub/bin:$PATH"
export PATH="$($HOME/.nub/bin/nub bin -g):$PATH"

# go
export PATH="/opt/go/bin:$PATH"
export PATH="$HOME/go/bin:$PATH"

export PATH="$HOME/dev/cadence/bin:$PATH"

""" }
"~/.zshrc/nub" = { block = """
export PATH="$HOME/.nub/bin:$PATH"
export PATH="$($HOME/.nub/bin/nub bin -g):$PATH"
""" }
