[dotfiles]
"~/.zshrc/uv" = { block = """
eval \"$(uv generate-shell-completion zsh)\"
export UV_PYTHON_PREFERENCE=only-managed
# Fix completions for uv run to autocomplete .py files
_uv_run_mod() {
    if [[ "$words[2]" == "run" && "$words[CURRENT]" != -* ]]; then
        _arguments '*:filename:_files -g "*.py"'
    else
        _uv "$@"
    fi
}
compdef _uv_run_mod uv

""" }
"~/.zshrc/bun" = { block = """
# bun completions
[ -s "/home/ted/.bun/_bun" ] && source "/home/ted/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
""" }

"~/.zshrc/worktrunk" = { block = "if command -v wt >/dev/null 2>&1; then eval \"$(command wt config shell init zsh)\"; fi" }
"~/.config/worktrunk/config.toml" = { source = "worktrunk/config.toml", mode = "symlink" }

"~/.config/nvim_native" = { source = "nvim_native", mode = "symlink" }
"~/.config/herdr" = { source = "herdr", mode = "symlink-each" }

"~/.pi" = { source = "agents/pi", mode = "symlink-each" }
"~/.claude" = { source = "agents/claude", mode = "symlink-each" }
# "~/.codex" = { source = "agents/claude", mode = "symlink-each" }

[tools]
node = "latest"
npm = "latest"
"npm:wrangler" = "latest"
"npm:oxlint" = "latest"
"npm:oxfmt" = "latest"
bun = "latest"
nub = "latest"
uv = "latest"
ty = "latest"
ruff = "latest"
worktrunk = "latest"
"npm:skills" = "latest"
"npm:@openai/codex" = "latest"
"claude" = "latest"
