git:
  commit:
    signOff: true

customCommands:
  - key: "F"
    command: "git fetch --prune"
    context: localBranches
    stream: true
  - key: "F"
    command: "git fetch --prune"
    context: remotes
    stream: true
