git:
  commit:
    signOff: true
customCommands:
  - key: "F"
    command: "git fetch --prune"
    context: localBranches
    output: log
  - key: "F"
    command: "git fetch --prune"
    context: remotes
    output: log
