model = "gpt-5.6-sol"
model_reasoning_effort = "medium"
personality = "pragmatic"
plan_mode_reasoning_effort = "high"
approvals_reviewer = "user"
service_tier = "default"
sandbox_mode = "workspace-write"

[features]
hooks = true
context_management.experimental_mode = true

[tui]
status_line = ["current-dir", "git-branch", "model-with-reasoning", "context-used"]

[desktop]
appearanceTheme = "system"
appearanceLightCodeThemeId = "rose-pine"
appearanceDarkCodeThemeId = "rose-pine"
useFontSmoothing = true
followUpQueueMode = "steer"
composerEnterBehavior = "cmdAlways"
preventSleepWhileRunning = true
keepRemoteControlAwakeWhilePluggedIn = true
git-branch-prefix = ""
notifications-turn-mode = "always"
conversationDetailMode = "STEPS_PROSE"
worktree-auto-cleanup-enabled = false
show-context-window-usage = true
dock-icon-preference = "app-default"
mac-menu-bar-enabled = false
enabled-reasoning-efforts = ["low", "medium", "high", "xhigh"]
defaultTerminalLocation = "right"

[desktop.appearanceLightChromeTheme]
accent = "#d7827e"
contrast = 45
ink = "#575279"
opaqueWindows = true
surface = "#faf4ed"

[desktop.appearanceLightChromeTheme.fonts]
code = "JetBrainsMono Nerd Font"

[desktop.appearanceLightChromeTheme.semanticColors]
diffAdded = "#56949f"
diffRemoved = "#797593"
skill = "#907aa9"

[desktop.appearanceDarkChromeTheme]
accent = "#ea9a97"
contrast = 60
ink = "#e0def4"
opaqueWindows = true
surface = "#232136"

[desktop.appearanceDarkChromeTheme.fonts]
code = '"JetBrainsMono Nerd Font"'

[desktop.appearanceDarkChromeTheme.semanticColors]
diffAdded = "#9ccfd8"
diffRemoved = "#908caa"
skill = "#c4a7e7"

[desktop.open-in-target-preferences]
global = "zed"
